set nocp
set magic							            " 设置 regulation express
set showmatch
set autoindent                    "自动对齐
set matchtime=2
set nowrap
set incsearch
set noswapfile
set ignorecase

" indent default setting
set tabstop=2
set expandtab
set smartindent                   "智能对齐
set shiftwidth=2
set softtabstop=2

set scrolloff=3							      " 光标移动到buffer的顶部和底部时保持3行距离
set laststatus=2						      " 启动显示状态行(1),总是显示状态行(2)
set history=1000 						      " 历史记录数量
set selection=inclusive           "
set backspace=indent,eol,start

syntax on
filetype on
syntax enable
filetype plugin on
filetype indent on

set pumheight=20
set completeopt=menu,menuone

set foldenable				  			" 开始折叠
set foldmethod=syntax					" 设置语法折叠
set foldlevelstart=99					" 打开文件是默认不折叠代码

"color monokai
set hidden
color molokai

let mapleader=','

" keymapping
let g:NERDTreeDirArrows = 1
let g:NERDTreeGlyphReadOnly = "RO"
let g:NERDTreeDirArrowExpandable = '▸'
let g:NERDTreeDirArrowCollapsible = '▾'
let g:NERDTreeNodeDelimiter = '\u00a0'
let NERDTreeIgnore=['\.pyc','\~$','\.swp','\.o']


"""""""""""""""""""""""""""""Bundle settings""""""""""""""""""""""""""
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

Bundle 'ctrlp.vim'
Bundle 'EasyMotion'
Bundle 'synmark.vim'
Bundle 'gmarik/vundle'
Bundle 'majutsushi/tagbar'
Bundle 'ap/vim-buftabline'
Bundle 'The-NERD-Commenter'
Bundle 'Valloric/ListToggle'
Bundle 'scrooloose/nerdtree'
"Bundle 'davidhalter/jedi-vim'
Bundle 'Valloric/YouCompleteMe'
Bundle 'skywind3000/asyncrun.vim'
Bundle 'hynek/vim-python-pep8-indent'
Bundle 'octol/vim-cpp-enhanced-highlight'

filetype plugin indent on
""""""""""""""""""""""""""""""""" Bundle END""""""""""""""""""""""""""

let g:cpp_class_scope_highlight = 1

"""""""""""""""""""""" configure for youcompleteme """"""""""""""""""""""""""""""
let g:ycm_confirm_extra_conf=0
let g:ycm_show_diagnostics_ui = 0
let g:ycm_complete_in_strings = 0
"let g:ycm_goto_buffer_command = 'vertical-split'
let g:ycm_global_ycm_extra_conf = '~/.vim/.ycm_extra_conf.py'
nnoremap <leader>gd :YcmCompleter GoToDefinitionElseDeclaration<CR>

"====================== asyncrun cmd config ==============
augroup vimrc
  autocmd User AsyncRunStart call asyncrun#quickfix_toggle(8, 1)
augroup END

nnoremap ;  :
inoremap jj <ESC>
nnoremap <leader>w <c-w>w
nnoremap <Leader>ch :A<CR>

" toggle tagbar
noremap <Leader>tt  :TagbarToggle<CR>
" toggle siderbar
noremap <leader>ts  :NERDTreeToggle<CR>
" toggle quickfix
nnoremap <leader>tq :call asyncrun#quickfix_toggle(8)<cr>
" toggle fold
nnoremap <leader>tf @=((foldclosed(line('.')) < 0) ? 'zc' : 'zo')<CR>
" go recent file
nnoremap <leader>gr :bp<CR>
nnoremap <leader>gn :bNext<CR>
" go buffer
set wildchar=<Tab> wildmenu wildmode=full
nnoremap <leader>gt :buffers<CR>:buffer<Space>
" search current word in workdir
nnoremap <leader>fc :AsyncRun grep -rwn <cword> .<cr>
" search directory
nnoremap <leader>fd :AsyncRun grep -rwn <cword> .


" win switch and banner
let i = 1
while i <= 5
    execute 'nnoremap <Leader>' . i . ' :' . i . 'wincmd w<CR>'
    let i = i + 1
endwhile
function! WindowNumber()
    return tabpagewinnr(tabpagenr())
endfunction
set statusline=b:[%n]w:[%{WindowNumber()}]\ f:%t\ \ %h%m%r%=\ m:[%{mode()}]\ c:[%c]\ l:[%l/%L]


" ========================== end ============================

highlight WhitespaceEOL ctermbg=red guibg=red
match WhitespaceEOL /\s\+$/

function RemoveTrailingSpace()
  if &ft != "diff"
    let b:curcol = col(".")
    let b:curline = line(".")
    silent! %s/\s\+$//
    call cursor(b:curline, b:curcol)
  endif
endfunction

autocmd BufReadPost * if line("'\"") > 0|if line("'\"") <= line("$")|exe("norm '\"")|else|exe "norm $"|endif|endif

python << EOF
import sys
import os
sys.path.insert(0, os.getcwd())
EOF

au BufNewFile,BufRead python
    \ set tabstop=4 |
    \ set expandtab |
    \ set autoindent |
    \ set shiftwidth=4 |
    \ set textwidth=79 |
    \ set softtabstop=4 |
    \ set fileformat=unix |

" c++0x lambda expr indent
au Filetype cpp,c
    \ setlocal cindent |
    \ setlocal cinoptions=l1 |
    \ setlocal cinoptions+=:0 |
    \ setlocal cino=l1,j1,(0,ws,Ws |
    \ setlocal expandtab tabstop=2 shiftwidth=2 |
