unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

if-shell "tmux has-session" "attach" "new"

# 只在复制模式显示滚动条(推荐)
if -b '[ #{version} >= 3.6 ]' {
    set -g pane-scrollbars modal
    set -g pane-scrollbars-position right
}

set -g mouse on
set -g base-index         1     # 窗口编号从 1 开始计数
set -g pane-base-index    1     # 窗格编号从 1 开始计数
set -g renumber-windows   on    # 关掉某个窗口后，编号重排
# set -g default-terminal "tmux-256color"
set -g default-terminal "xterm-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# 配置文件reload
# Reload config
bind r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded"
# Rename current session
bind R command-prompt -p "Rename session:" -I "#S" "rename-session '%%'"

# 重新绑定纵向和横向切分window快捷键。|，-，更直观地表明了切割方向
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Pane 切换，用 hjkl，保持和 nvim 一致
bind -r h select-pane -L
bind -r l select-pane -R
bind -r k select-pane -U
bind -r j select-pane -D
# 调整 pane 大小
bind -r H resize-pane -L 5
bind -r L resize-pane -R 5
bind -r K resize-pane -U 5
bind -r J resize-pane -D 5


bind v copy-mode
bind Escape copy-mode
bind -T copy-mode-vi i send -X cancel
bind -T copy-mode-vi Escape send -X cancel
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi V send -X select-line
bind -T copy-mode-vi C-v send -X rectangle-toggle
bind -T copy-mode-vi y send -X copy-selection-and-cancel

set -wg mode-keys         vi                         # 进入复制模式的时候使用 vi 键位（默认是 EMACS）
setw -g mode-style "bg=#3c3836,fg=#ebdbb2"           # 进入 copy-mode 时的整体背景（可选）

# 状态栏, 部分会被主题插件覆盖
set -g status on
set -g status-interval  1                               # 状态栏刷新时间
set -g status-position  bottom
set -g status-justify   left

set -g status-style "bg=black, fg=#a89984"                                    # 状态栏前景背景色
set -g status-left  "#{?client_prefix,#[bg=#fe8019]🐼,#[bg=#a89984]🐶}[#S] "  # 状态栏左侧
set -g status-right "#[bg=#a89984,fg=#3c3836] %Y-%m-%d %H:%M"                 # 状态栏右侧

set -wg allow-rename      off                       # 禁止活动进程修改窗口名
set -wg automatic-rename  off                       # 禁止自动命名新窗口
set -wg monitor-activity  on                        # 非当前窗口有内容更新时在状态栏通知
set -wg window-status-format " #I.#W "              # 状态栏窗口名称格式
set -wg window-status-separator " "                 # 状态栏窗口名称之间的间隔
set -wg window-status-current-format " #I:#W#F "    # 状态栏当前窗口名称格式(#I：序号，#w：窗口名称，#F：间隔符)

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'

set -g @plugin 'egel/tmux-gruvbox'
set -g @tmux-gruvbox 'light256' # dark or 'dark256', 'light', 'light256'
set -g @tmux-gruvbox-left-status-a '#{?client_prefix,🐼,🐶}[#S]' # tmux's session name

#set -g @plugin 'OwlfaceGames/melangey_tmux'

run '~/.tmux/plugins/tpm/tpm'
